language: python

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"

branches:
  only:
    - master
    - 0.2.x

# command to install requirements
install:
  - pip install -r requirements-test.txt
  - pip install -r requirements.txt
  - pip install coveralls
  - python setup.py -q develop

# command to run tests, e.g. python setup.py test
script:
    - PYTHONPATH=$PYTHONPATH:. mamba --enable-coverage

after_success:
  coveralls
