language: python

python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"

branches:
  only:
    - master

install:
  - pip install -r requirements-test.txt
  - pip install coveralls
  - python setup.py -q develop

script:
    - PYTHONPATH=$PYTHONPATH:. mamba --enable-coverage

after_success:
  coveralls
